[project]
name = "estadistica-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "jinja2>=3.1.6",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
]
